### ISSUE TITLE
!

### ISSUE THREAD

**Issue by tunip3** [Nun-z/XboxRetailModeAppGuide#2]

**Comment by Nun-z** [comment]
You've returned to harass me?  It looks like further retaliation is in order @tunip3.

**Comment by tunip3** [comment]
No mate I got pissed and subsequently left a nasty message I am not here to harrass you. I don't understand what you mean by more retaliation when I have not done anything to you

**Comment by Nun-z** [comment]
You have banned me from your server.  You tried to force me to trash the guide I put a lot of effort into, and, despite not liking when others try to control me, I agreed to do so on the condition that you would allow me to own the source code for durango-ftp.  You then sent your goon to another Discord server to harass me.  After I forked the code you agreed to give me, you subsequently deleted my access to the private repo, automatically deleting my fork with all the effort I put into it.  I had to upload a very old backup.

**Comment by Nun-z** [comment]
![Deleted fork](https://user-images.githubusercontent.com/54733172/107905931-bdcfda00-6f04-11eb-8987-dd67e7855589.PNG)

**Comment by tunip3** [comment]
I never banned you from any server, I never sent anyone to do anything. Your access to got automatically wiped out by accident when I moved the FTP server to another organisation in order to make it easier to open source and collaborate on. I didn't ask you to trash the guide, I just wanted you to not post it until something else could be found that meant we weren't exclusively dependent on this for code execution on retail. If you want to actually talk you have my discord tag and you can message me if you would rather talk than simply act like a petulant child.

**Comment by Nun-z** [comment]
You're a liar and a cheat.  I have nothing further to say to you.
